# Generated by Django 5.2.4 on 2025-07-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False, verbose_name='メールID')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='タイトル')),
                ('sender', models.TextField(verbose_name='FROM')),
                ('recipients', models.TextField(verbose_name='TO')),
                ('cc', models.TextField(verbose_name='CC')),
                ('sent_at', models.DateField(verbose_name='受信日')),
                ('body', models.TextField(verbose_name='本文')),
                ('eml', models.BinaryField(blank=True, null=True, verbose_name='emlファイル')),
                ('insert_date', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'メール',
                'verbose_name_plural': 'メール',
                'db_table': 'mail',
            },
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('iattach_d', models.AutoField(primary_key=True, serialize=False, verbose_name='添付ファイルID')),
                ('attach_name', models.TextField(verbose_name='添付ファイル名')),
                ('attach_file', models.BinaryField(blank=True, null=True, verbose_name='添付ファイル')),
                ('email', models.ForeignKey(db_column='email_id', on_delete=django.db.models.deletion.CASCADE, to='mailviewer.mail', verbose_name='メールID')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
                'db_table': 'attach',
            },
        ),
    ]
